<?php

namespace App\Services\Payment;

use Stripe\Charge;
use Stripe\Stripe;
use App\Models\Reservation;
use Illuminate\Support\Facades\Log;

class PaymentService

{

    /**

     * Process a payment for a reservation.
     *
     * @param array $data An associative array containing the payment details:
     *                    - 'reservation_id': The ID of the reservation.
     *                    - 'amount': The amount to be charged.
     *                    - 'stripeToken': The token generated by Stripe.
     * @return StripeCharge|array The charge object if successful, or an error array if failed.
     */
    public function processPayment(array $data)
    {
        try {
            //Set stripe secret key
            Stripe::setApiKey(env('STRIPE_SECRET_KEY'));
            $reservation = Reservation::find($data['reservation_id']);

            if (!$reservation) {
                return ['status' => 'error', 'message' => 'Reservation not found.'];
            }

            if ($reservation->user_id !== auth()->id()) {
                return ['status' => 'error', 'message' => 'You do not have permission to pay for this reservation.'];
            }
            // Update the reservation with the payment value
            if ($reservation) {
                $reservation->payment_value = $data['amount'];
                $reservation->save();
            }

            // Payment processing
            $charge = Charge::create([
                'amount' => $data['amount'] * 100,
                'currency' => 'usd',
                'source' => $data['stripeToken'],
                'description' => 'API Payment Example',
            ]);

            return ['status' => 'success', 'charge' => $charge];

        } catch (\Exception $e) {
            Log::error('Error in paymentService@processPayment: ' . $e->getMessage());
            return ['status' => 'error', 'message' => 'An unexpected error occurred'];
        }
    }

    public function addprocessPayment(array $data)
    {
        try {
            Stripe::setApiKey(env('STRIPE_SECRET_KEY'));
            $reservation = Reservation::find($data['reservation_id']);

            if (!$reservation) {
                return ['status' => 'error', 'message' => 'Reservation not found.'];
            }

            if ($reservation->user_id !== auth()->id()) {
                return ['status' => 'error', 'message' => 'You do not have permission to pay for this reservation.'];
            }

            if ($reservation->payment_value == null) {
                return ['status' => 'error', 'message' => 'This invoice has not been paid.'];
            }

            $reservation->payment_value = $reservation->payment_value + $data['amount'];
            $reservation->save();

            $charge = Charge::create([
                'amount' => $data['amount'] * 100,
                'currency' => 'usd',
                'source' => $data['stripeToken'],
                'description' => 'API Payment Example',
            ]);

            return ['status' => 'success', 'charge' => $charge];
        } catch (\Exception $e) {
            Log::error('Error in paymentService@addprocessPayment: ' . $e->getMessage());
            return ['status' => 'error', 'message' => 'An unexpected error occurred'];
        }
    }
}
